### ISSUE TITLE
In 3rd test, typo in the copy

### ISSUE THREAD

**Issue by marineb** [learn-co-students/javascript-intro-to-looping-bootcamp-prep-000#9]
The line `describe('doWhile(array)', () => {` should be replaced by `describe('doWhileLoop(array)', () => {` to validate with what it is testing against.

**Comment by marineb** [comment]
(I would fix it myself but it doesn't look like I can fork this repo a second time).

**Comment by aturkewi** [comment]
Hey @marineb thanks for raising this issue an offering to fix it!

This is actually just a 'deploy' of our lab. If you ever want to raise an issue and make a PR on a lab, you want to go to the canonical version of the lab. You can get to it by click the Raise Issue button in Learn.

I've fixed this one with the following PR https://github.com/learn-co-curriculum/javascript-intro-to-looping/issues/18

Thanks again!

**Comment by marineb** [comment]
Oh cool. Thanks. Will do in the future!
